#!/bin/bash
# Lab migration script using git mv

echo "========================================"
echo "LAB MIGRATION TO PILLAR DIRECTORIES"
echo "========================================"
echo ""

# Read the JSON and perform migrations
# This is a simplified version - you can run git mv commands manually

echo "To migrate labs, run these git mv commands:"
echo ""
echo "# Operational Excellence (26 labs)"
echo "git mv compute/docker-ecr-url-checker operational-excellence/"
echo "git mv devops-cicd/cdk-constructs-lambda-api operational-excellence/"
echo "git mv devops-cicd/cloudformation-codepipeline-iac operational-excellence/"
echo "git mv devops-cicd/cloudformation-intrinsic-functions operational-excellence/"
echo "git mv devops-cicd/codedeploy-blue-green operational-excellence/"
echo "git mv devops-cicd/codeguru-code-reviews operational-excellence/"
echo "git mv devops-cicd/codepipeline-integration-testing operational-excellence/"
echo "git mv devops-cicd/codepipeline-unit-testing operational-excellence/"
echo "git mv devops-cicd/distributor-package-creation operational-excellence/"
echo "git mv databases/dynamodb-capacity-scaling operational-excellence/"
echo "git mv databases/dynamodb-streams-lambda operational-excellence/"
echo "git mv databases/dynamodb-tables-indexes operational-excellence/"
echo "git mv compute/ec2-troubleshooting-detective-controls operational-excellence/"
echo "git mv compute/eks-url-checker operational-excellence/"
echo "git mv modern-applications/event-driven-architecture operational-excellence/"
echo "git mv devops-cicd/eventbridge-automation operational-excellence/"
echo "git mv compute/fargate-ecs-deployment operational-excellence/"
echo "git mv compute/flask-elastic-beanstalk operational-excellence/"
echo "git mv compute/lambda-url-checker operational-excellence/"
echo "git mv ai-ml-applications/langchain-ai-development operational-excellence/"
echo "git mv monitoring/monitoring-applications-infrastructure operational-excellence/"
echo "git mv monitoring/security-monitoring-cloudwatch-alarms operational-excellence/"
echo "git mv modern-applications/serverless-development operational-excellence/"
echo "git mv devops-cicd/systems-manager-automation-resize operational-excellence/"
echo "git mv security/waf-web-application-protection operational-excellence/"
echo "git mv ai-ml-applications/bedrock-console-introduction operational-excellence/"
echo ""
echo "# Security (21 labs)"
echo "git mv security/api-gateway-cognito-authorizer security/"
echo "git mv ai-ml-applications/bedrock-guardrails-security security/"
echo "git mv security/cloudtrail-log-analysis security/"
echo "git mv security/cognito-user-authentication security/"
echo "git mv databases/dynamodb-encryption security/"
echo "git mv compute/ec2-instance-metadata-service security/"
echo "git mv security/guardduty-threat-detection security/"
echo "git mv security/iam-policy-management security/"
echo "git mv security/kms-encryption security/"
echo "git mv networking/network-security-groups security/"
echo "git mv security/secrets-manager-rotation security/"
echo "git mv security/security-hub-compliance security/"
echo "git mv storage/s3-bucket-policies security/"
echo "git mv storage/s3-encryption security/"
echo "git mv storage/s3-versioning-lifecycle security/"
echo "git mv networking/vpc-flow-logs security/"
echo "git mv networking/vpc-peering security/"
echo "git mv networking/vpc-private-subnets security/"
echo "git mv networking/vpc-public-subnets security/"
echo "git mv networking/vpc-security-groups security/"
echo "git mv security/waf-rate-limiting security/"
echo ""
echo "# Cost Optimization (6 labs)"
echo "git mv compute/ec2-cost-optimization cost-optimization/"
echo "git mv compute/ec2-rightsizing cost-optimization/"
echo "git mv databases/rds-cost-optimization cost-optimization/"
echo "git mv storage/s3-intelligent-tiering cost-optimization/"
echo "git mv storage/s3-storage-classes cost-optimization/"
echo "git mv compute/lambda-cost-optimization cost-optimization/"
echo ""
echo "# Reliability (4 labs)"
echo "git mv databases/rds-automated-backups reliability/"
echo "git mv databases/rds-multi-az reliability/"
echo "git mv databases/rds-read-replicas reliability/"
echo "git mv compute/ec2-auto-scaling reliability/"
echo ""
echo "# Performance Efficiency (1 lab)"
echo "git mv networking/cloudfront-distribution performance-efficiency/"
echo ""

echo "Or run: bash migrate_labs.sh | grep 'git mv' | bash"
